base_url = "https://art3mis.pm"
title = "art3mis pm"

default_language = "en"
minify_html = true
generate_feed = true

[markdown]
	highlight_code = true
	render_emoji = true
	external_links_target_blank = true

[extra]
	d3_nav = [
		{ name = "HOME", path = "/" },
		{ name = "POSTS", path = "/posts/" },
  	]
	d3_author = "art3mis"
